name = "chat-ui"        # Can match GitHub or just be descriptive
compatibility_date = "2024-10-14"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "ceo_orders"
database_id = "fdc684fb-d1c5-426c-b6c4-a00402afea12"

[[kv_namespaces]]
binding = "MAINTENANCE_KV"
id = "c10da595a2204dac8e35fb87a757e0fe"
preview_id = "5ff737d6327e4f37b1b8c3976a9210d1"

[vars]
PI_NETWORK = "testnet"
